version: '2'
services:

  greeting:
    build: application
    ports:
      - 8081:8080
    environment:
          ACTOR_PROFILE: greeting

  hello:
    build: application
    ports:
      - 8082:8080
    environment:
          ACTOR_PROFILE: hello